# config.yaml file for configuring blue tooth sensors

mqtt_server_url: "tcp://172.148.5.11:1883"
mqtt_base_topic: "homeassistant/sensor/ble-temp/"

# set to empty if not used
mqtt_username: "mosquitto"
mqtt_password: "mosquitto_pass"

# bluetooth adapter = integer number of bluetooth devices, run hciconfig to see your adapters, 1st adapter is referenced as 0 in this program
bluetooth_adapter: 0

# scan type = 0 for passive, 1 for active advertising scan, some BLE sensors only share data on type 4 response active advertising packets
scan_type: 1

# integer number that is multiplied by 0.625 to set advertising scanning window in milliseconds. Try 100 to start.
scan_window: 100

# integer number that is multiplied by 0.625 to set advertising scanning interval in milliseconds. Try 1000 to start.
scan_interval: 1000

# 0 to publish via MAC, 1 to publish via name 
# not implemented yet
publish_type: 0

# create HomeAssistant autoconfiguration entries, 1 to enable, 0 to disable
# not implemented yet
auto_configure: 1

# set syslog destination
# not implemented yet
syslog_address: "192.168.2.5"

# set log level
# 0 = LOG_EMERG - system is unusable
# 1 = LOG_ALERT	- action must be taken immediately
# 2 = LOG_CRIT - critical conditions
# 3 = LOG_ERR - error conditions
# 4 = LOG_WARNING - warning conditions
# 5 = LOG_NOTICE - normal but significant condition
# 6 = LOG_INFO - informational
# 7 = LOG_DEBUG - debug-level messages

logging_level: "7"

# Sensor types:
#  1 = Xiaomi LYWSD03MMC-ATC   https://github.com/atc1441/ATC_MiThermometer
#  2 = Govee H5052 (type 4 advertising packets)
#  3 = Govee H5072
#  4 = Govee H5102
#  5 = Govee H5075
#  6 = Govee H5074 (type 4 advertising packets)
# 99 = Display raw type 0 and type 4 advertising packets for this BLE MAC address

sensors:
  - name: "Living Room"
    location: "Living Room"
    type: 1
    mac: "DD:C1:38:70:0C:24"

  - name: "Shared Bathroom"
    Location: "Shared Bathroom"
    ype: 3
    mac: "DD:C1:38:AC:77:44"

  - name: "Attic"
    location: "Attic"
    type: 3
    mac: "DD:12:1D:22:80:77"

  - name: "LYWSD03MMC test"
    location: "Garage"
    type: 99
    mac: "DD:C1:38:AC:28:A2"
